version: '3.8'

services:
  backend:
    build:
      context: ./server
    container_name: dev-assistant-ai-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
    container_name: dev-assistant-ai-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
